name: Master Workflow
# This workflow is triggered on pushes/pull requests to master
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      java: 12 
    # Job name
    name: Build Alerting with JDK ${{ java }}
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses the checkout Github action: https://github.com/actions/checkout
      - name: Checkout Branch
        uses: actions/checkout@v1
      # This step uses the setup-java Github action: https://github.com/actions/setup-java
      - name: Set Up JDK ${{ java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ java }}
      - name: Build with Gradle
        run: ./gradlew build
      - name: Create Artifact Path
        run: |
          mkdir -p alerting-artifacts
          cp ./build/distributions/*.zip alerting-artifacts
      # This step uses the upload-artifact Github action: https://github.com/actions/upload-artifact
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: alerting-artifacts
          path: alerting-artifacts
